swagger: "2.0"
info:
  description: "Authors Haven - A social platform for the creative at heart."
  version: "1.0.0"
  title: "Authors Haven"
  license:
    name: "MIT"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api/v1"
tags:
- name: "user"
  description: "User operations"
- name: "articles"
  description: "Articles operations"
schemes:
  - "https"
  - "http"
paths:
  /users:
    post:
      tags:
      - "Auth"
      summary: "Create user"
      description: "Creates a new user in the application"
      operationId: "createUser"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "formData"
        name: "username"
        description: "The unique username"
        required: true
        type: "string"
        format: "text"
        minLength: 4
        maxLength: 100
      - in: "formData"
        name: "email"
        description: "The unique user email"
        required: true
        type: "string"
        format: "email"
        minLength: 5
        maxLength: 255
      - in: "formData"
        name: "password"
        description: "The user password"
        required: true
        type: "string"
        format: "password"
        minLength: 5
        maxLength: 255
      - in: "formData"
        name: "firstname"
        description: "First name of user"
        required: false
        type: "string"
        format: "text"
        minLength: 2
        maxLength: 100
      - in: "formData"
        name: "lastname"
        description: "Last name of user"
        required: false
        type: "string"
        format: "text"
        minLength: 2
        maxLength: 100
      - in: "formData"
        name: "middlename"
        description: "Middle name of user"
        required: false
        type: "string"
        format: "text"
        minLength: 2
        maxLength: 100
      responses:
        201:
          description: "User created successfully"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Invalid email/password supplied"
    get:
      tags:
      - "users"
      summary: "Users with profiles"
      description: "Returns all users and their corresponding profiles"
      operationId: "getUsers"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "fail"
      security:
      - api_key: []
    put:
      tags:
      - "Profile"
      summary: "Update User Profile"
      description: "Returns the Updated User Details"
      operationId: "updateProfile"
      produces:
      - "application/json"
      parameters:
      - in: "formData"
        name: firstname
        required: false
        type: string
        description: "first name"
      - in: "formData"
        name: lastname
        required: false
        type: string
        description: "last name"
      - in: "formData"
        name: bio
        required: false
        type: text
        description: "bio"
      - in: "formData"
        name: avatar
        required: false
        type: string
        description: "Avatar URL"
      - in: "formData"
        name: location
        required: false
        type: string
        description: "Location"
      - in: "formData"
        name: phone
        required: false
        type: integer
        description: 'Phone Number'
        minLength: 11
        maxLength: 14
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Invalid token supplied: format Bearer <token>"
        401:
          description: "Invalid Token Provided"
      security:
      - api_key: []
  /profiles/{username}:
    get:
      tags:
      - "Profile"
      summary: "User Profile details"
      description: "Returns the profile details of a user"
      operationId: "getProfile"
      produces:
      - "application/json"
      parameters:
        - in: path
          name: username
          required: false
          type: string
          description: "User's username"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/ApiResponse"
        404:
          description: "fail"
  /auth/login:
    post:
      tags:
      - "Auth"
      summary: "User login"
      description: "Logs user into the system"
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "formData"
        description: "The email for login"
        required: true
        type: "string"
        format: "email"
        minLength: 5
        maxLength: 255
      - name: "password"
        in: "formData"
        description: "The password for login in clear text"
        required: true
        type: "string"
        format: "password"
        minLength: 5
        maxLength: 255
      responses:
        200:
          description: "login successful"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Invalid email/password supplied"
  /articles:
    post:
      tags:
      - "article"
      summary: "Create article"
      description: "Creates a new article in the application"
      operationId: "createArticle"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "formData"
        name: "title"
        description: "The article title"
        required: true
        type: "string"
        format: "text"
        minLength: 4
        maxLength: 500
      - in: "formData"
        name: "body"
        description: "The article body"
        required: true
        type: "string"
        format: "text"
        minLength: 4
      - in: "formData"
        name: "image"
        description: "The image url"
        required: false
        type: "string"
        format: "text"
      responses:
        200:
          description: "Article created successfully"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Title/ body is not allowed to be empty"
      security:
      - api_key: []
    get:
      tags:
      - "article"
      summary: "user can get all articles"
      description: "Returns all available articles"
      operationId: "getArticles"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "fail"
    delete:
      tags:
      - "article"
      summary: "user can delete an articles"
      description: "Deletes an article in application"
      operationId: "deleteArticles"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "fail"
      security:
      - api_key: []
    put:
      tags:
      - "article"
      summary: "Update article"
      description: "Updates an article in the application"
      operationId: "updateArticle"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "formData"
        name: "title"
        description: "The article title"
        required: true
        type: "string"
        format: "text"
        minLength: 4
        maxLength: 500
      - in: "formData"
        name: "body"
        description: "The article body"
        required: true
        type: "string"
        format: "text"
        minLength: 4
      - in: "formData"
        name: "image"
        description: "The image url"
        required: false
        type: "string"
        format: "text"
      responses:
        200:
          description: "Article updated successfully"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Title/ body is not allowed to be empty"
  /articles/{slug}:
    get:
      tags:
      - "article"
      summary: "user can get all articles"
      description: "Returns all available articles"
      operationId: "getArticles"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "fail"
    delete:
      tags:
      - "article"
      summary: "user can delete an articles"
      description: "Deletes an article in application"
      operationId: "deleteArticles"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "fail"
      security:
      - api_key: []
    put:
      tags:
      - "article"
      summary: "Update article"
      description: "Updates an article in the application"
      operationId: "updateArticle"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "formData"
        name: "title"
        description: "The article title"
        required: true
        type: "string"
        format: "text"
        minLength: 4
        maxLength: 500
      - in: "formData"
        name: "body"
        description: "The article body"
        required: true
        type: "string"
        format: "text"
        minLength: 4
      - in: "formData"
        name: "image"
        description: "The image url"
        required: false
        type: "string"
        format: "text"
      responses:
        200:
          description: "Article updated successfully"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Title/ body is not allowed to be empty"
  /articles/{slug}/rate:
    post:
      tags:
      - "article"
      summary: "Rate Article"
      description: "Rates an article"
      operationId: "rateArticle"
      produces:
      - "application/json"
      parameters:
      - name: "slug"
        in: "path"
        description: "Slug of the article to be rated"
        required: true
        type: "string"
        format: "slug"
      - name: "rate"
        in: "formData"
        description: "Rating you are giving to the article"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Rating has been updated"
          schema:
            $ref: "#/definitions/ApiResponse"
        201:
          description: "New rating has been made"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Invalid rating supplied"
        404:
          description: "Article does not exist"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "string"
        format: "int64"
      username:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      firstname:
        type: "string"
      lastname:
        type: "string"
      middlename:
        type: "string"
      active:
        type: boolean
  Profile:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
  Article:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      body:
        type: "string"
      image:
      userId:
        type: "string"
      bio:
        type: "string"
      avatar:
        type: "string"
      phone:
        type: "string"
      location:
        type: "string"
  Rating:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      userId:
        type: "string"
        format: "uuid"
      articleId:
        type: "string"
        format: "uuid"
      ratings:
        type: "integer"
  ApiResponse:
    type: "object"
    properties:
      status:
        type: "integer"
        format: "int32"
      data:
        type: "object"
        items:
          type: "object"
externalDocs:
  description: "Find out more about Author's Haven"
  url: "https://github.com/andela/kingsmen-ah-backend"
