swagger: "2.0"
info:
  description: "Authors Haven - A social platform for the creative at heart."
  version: "1.0.0"
  title: "Authors Haven"
  license:
    name: "MIT"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api"
tags:
- name: "user"
  description: "User operations"
schemes:
  - "https"
  - "http"
paths:
  /users:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "Creates a new user in the application"
      operationId: "createUser"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "formData"
        name: "username"
        description: "The unique username"
        required: true
        type: "string"
        format: "text"
        minLength: 4
        maxLength: 100
      - in: "formData"
        name: "email"
        description: "The unique user email"
        required: true
        type: "string"
        format: "email"
        minLength: 5
        maxLength: 255
      - in: "formData"
        name: "password"
        description: "The user password"
        required: true
        type: "string"
        format: "password"
        minLength: 5
        maxLength: 255
      - in: "formData"
        name: "bio"
        description: "Brief information about the user"
        required: false
        type: "string"
        format: "text"
        minLength: 5
        maxLength: 500
      - in: "formData"
        name: "image"
        description: "The user image"
        required: false
      - in: "formData"
        name: "favorites"
        description: "The user's favorite article"
        required: false
        type: array
        items:
          type: "string"
      - in: "formData"
        name: "following"
        description: "Number of people user is following"
        required: false
        type: "integer"
      responses:
        201:
          description: "User created successfully"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Invalid email/password supplied"
  /user:
    post:
      tags:
      - "user"
      summary: "User login"
      description: "Logs user into the system"
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "formData"
        description: "The email for login"
        required: true
        type: "string"
        format: "email"
        minLength: 5
        maxLength: 255
      - name: "password"
        in: "formData"
        description: "The password for login in clear text"
        required: true
        type: "string"
        format: "password"
        minLength: 5
        maxLength: 255
      responses:
        200:
          description: "login successful"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Invalid email/password supplied"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      bio:
        type: "string"
      image:
        type: "string"
      favorites:
        type: "array"
        items:
          type: "string"
      following:
        type: "integer"
        format: "int64"
  ApiResponse:
    type: "object"
    properties:
      status:
        type: "integer"
        format: "int32"
      errors:
        type: "object"
        items:
          type: "object"
externalDocs:
  description: "Find out more about Author's Haven"
  url: "https://github.com/andela/kingsmen-ah-backend"
  